upstream docker-tester1 {
    server tester1:80;
}

server {
    listen 80;
    server_name *.sgshami.com;
    return 301 https://sgshami.com$request_uri;
}

server {
    listen 443 ssl;
    server_name tester1.sgshami.com;
    
    ssl_certificate /etc/ssl/sgshami.com.pem;
    ssl_certificate_key /etc/ssl/sgshami.com.key;

    proxy_pass         http://docker-tester1;
    proxy_redirect     off;
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Host $server_name;
}
