version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=sgshami@gmail.com
      # - CF_DNS_API_TOKEN=YOUR_API_TOKEN
      - CF_API_KEY=v1.0-838b85579937f68bb110864c-1f03b29792ef823d121b5a37d25fcca6fe6ce312f4ee8a4c93ce5ae232e5b45e35c4afaaaf2cc6e38e1e3667e849dceac72047129f94397b05530292699b167a93eb1d49e8f05f96c5
      # be sure to use the correct one depending on if you are using a token or key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/sgshami/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/sgshami/traefik/data/acme.json:/acme.json
      - /home/sgshami/traefik/data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`192.168.1.106`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=sgshami:$$apr1$$5Mk6GtHM$$heYNvJHtlXSA6KZK1gdME."
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`192.168.1.106`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=sgshami.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.sgshami.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
