services:
  nginx:
    image: nginx:1.25.5
    container_name: nginx
    volumes:
      - ./homepage:/var/www/html
      - ./config:/etc/nginx/conf.d
      - ~/ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped