services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    # depends_on:
    #   - jellyfin
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse-proxy
    volumes:
      - ./homepage:/var/www/html
      - ./templates:/etc/nginx/templates
      - ~/ssl:/etc/ssl:ro
    # environment:
    #   - MAIN_HOST=sgshami.com www.sgshami.com default_server
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    command: bash -c "ls -l /etc/ssl"

networks:
  reverse-proxy:
    name: reverse-proxy
    driver: bridge