services:
  nginx:
    image: nginx:1.26.0
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse-proxy
    volumes:
      - ./homepage:/var/www/html
      - ./config:/etc/nginx/conf.d
      - ../../ssl:/etc/ssl:ro
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  reverse-proxy:
    external: true
