services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - jellyfin
    ports:
      - 443:443
    volumes:
      - ./homepage:/var/www/html
      - ./config:/etc/nginx/conf.d
      - ~/ssl:/etc/ssl
    networks:
      - reverse-proxy
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=3000 # Set User to user with volume permission
      - PGID=3000 # Set Group to group with volume permission
      - TZ=US/Mountain
    volumes:
      - /mnt/nfs/media/jellyfin:/config
      - /mnt/nfs/media/tv-shows:/data/tvshows
      - /mnt/nfs/media/movies:/data/movies
    ports:
      - 8096:8096
    networks:
      - reverse-proxy
    restart: unless-stopped

networks:
  reverse-proxy:
    name: reverse-proxy
    driver: bridge