services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    # depends_on:
    #   - jellyfin
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./homepage:/var/www/html
      - ./config:/etc/nginx/conf.d:ro
      - ~/ssl:/etc/ssl:ro
#     networks:
#       - reverse-proxy
#     healthcheck:
#       test: curl --fail http://localhost || exit 1
#       interval: 60s
#       retries: 5
#       start_period: 20s
#       timeout: 10s

# networks:
#   reverse-proxy:
#     name: reverse-proxy
#     driver: bridge

# NGINX debug command that works:
# sudo docker run -v ./config:/etc/nginx/conf.d -v ./homepage:/var/www/html -v ~/ssl:/etc/ssl -p 443:443 -d nginx nginx-debug -g 'daemon off;'