services:
  nginx:
    image: nginx:1.25.5
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse-proxy
    volumes:
      - ./homepage:/var/www/html
      - ./config:/etc/nginx/conf.d
      - ~/ssl:/etc/ssl
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  reverse-proxy:
    name: reverse-proxy
    driver: bridge