services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    # depends_on:
    #   - jellyfin
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./homepage:/var/www/html
      - ./config:/etc/nginx/conf.d
      - ~/ssl:/etc/ssl
    networks:
      - reverse-proxy
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  reverse-proxy:
    name: reverse-proxy
    driver: bridge