services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-java
    networks:
      - minecraft-server
      - reverse-proxy
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /mnt/ssd/minecraft/java:/data

  mc-bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: mc-bedrock
    networks:
      - minecraft-server
      - reverse-proxy
    ports:
      - 19132:19132/udp
    environment:
      EULA: "TRUE"
    volumes:
      - /mnt/ssd/minecraft/bedrock:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  minecraft-server:
    driver: bridge
  reverse-proxy:
    external: true
