services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordlynx
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PRIVATE_KEY=${NORD_PRIVATE_KEY}
      - NET_LOCAL=10.0.0.0/24
      - TZ=America/Denver
    ports:
      - "8080:8080"
    networks:
      - vpn-network
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - nordlynx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/nfs/media/config/:/config
      - /mnt/nfs/media/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

networks:
  vpn-network:
    name: vpn-network
    driver: bridge