services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    hostname: nordlynx
    container_name: nordlynx
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PRIVATE_KEY=${NORD_PRIVATE_KEY}
      - NET_LOCAL=10.0.0.0/16,192.168.50.0/24
      - TZ=America/Denver
    ports:
      - 8080:8080 # qBittorrent GUI
      - 33445:33445 # qBittorrent Download
      - 33445:33445/udp # qBittorrent Download
      - 9696:9696 # Prowlarr
      - 8686:8686 # Lidarr
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # Recomended if using ipv4 only
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - nordlynx
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Denver
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /opt/config/qbittorrent:/config
      - /mnt/nfs/media/downloads:/downloads
    network_mode: service:nordlynx
    # ports: # These will not work. Ports should be declared via VPN.
    #   - 8080:8080
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Denver
    volumes:
      - /opt/config/prowlarr:/config
    restart: unless-stopped
    network_mode: service:nordlynx
    depends_on:
      - nordlynx
      - qbittorrent
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1024
      - PGID=101
      - TZ=America/Denver
    volumes:
      - /opt/config/sonarr:/config
      - /mnt/nfs/media/tv-shows:/tv
      - /mnt/nfs/media/downloads/tv-shows:/downloads/tv-shows
    restart: unless-stopped
    network_mode: service:nordlynx
    depends_on:
      - prowlarr
      - qbittorrent
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Denver
    volumes:
      - /opt/radarr:/config
      - /mnt/nfs/media/movies:/movies
      - /mnt/nfs/media/downloads/movies:/downloads/movies
    restart: unless-stopped
    network_mode: service:nordlynx
    depends_on:
      - prowlarr
      - qbittorrent
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/Denver
    volumes:
      - /opt/lidarr:/config
      - /mnt/nfs/media/music:/music
      - /mnt/nfs/media/downloads/music:/downloads/music
    restart: unless-stopped
    network_mode: service:nordlynx
    depends_on:
      - prowlarr
      - qbittorrent

# Removed. This can be added later. Possible issue with filling up space.
  # jellyseerr:
  #   image: ghcr.io/fallenbagel/jellyseerr:latest
  #   container_name: jellyseerr
  #   environment:
  #     - LOG_LEVEL=info
  #     - TZ=America/Denver
  #   ports:
  #     - 5055:5055
  #   volumes:
  #     - /opt/jellyseerr:/app/config
  #   restart: unless-stopped
  #   depends_on:
  #     - radarr
  #     - sonarr
