services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    hostname: nordlynx
    container_name: nordlynx
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PRIVATE_KEY=${NORD_PRIVATE_KEY}
      - NET_LOCAL=10.0.0.0/24
      - TZ=America/Denver
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - nordlynx
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=America/Denver
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/nfs/media/config/qbittorrent:/config
      - /mnt/nfs/media/downloads:/downloads
    network_mode: service:nordlynx
    # ports: # These will not work. Ports should be declared via VPN.
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    restart: unless-stopped