services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordlynx
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PRIVATE_KEY=${NORD_PRIVATE_KEY}
      - NET_LOCAL=10.0.0.0/24
      - TZ=America/Denver
    ports:
      - "8080:8080"
    networks:
      - vpn-network

networks:
  vpn-network:
    name: vpn-network
    driver: bridge