services:
  nord:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN   # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=10.0.0.0/24
    ports: # List all ports that need to be accessed inside local network here.
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only

networks:
  vpn-network:
    name: vpn-network
    driver: bridge