version: "3"
services:
  client:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/sgshami/nginx/My-Site:/usr/share/nginx/html
      - /home/sgshami/nginx/config:/etc/nginx/conf
      - /home/sgshami/nginx/ssl/sgshami_com:/etc/ssl
